#!/usr/bin/perl
use Time::Local;
use Getopt::Std;
use POSIX qw(strftime);
my $USAGE =<<USAGE;
     Usage:
       ./Capture_dns_query_generator.pl -m <Member's separated by ':'> -q <Number of Query Patterns> -d <MM:DD:YYYY> -t <query|response|all>

     Example:
       ./Capture_dns_query_generator.pl -m member1.com:member2.com:member3.com -q 50000 -d 02:08:2016 -t all

      -m : Member names should be in ':' separeted format.        default member is ib-11-11-11-11.testing.com                   #optional
      -q : Number of Query Patterns.                              default value is '2000'                                        #optional
      -d : Date in MM:DD:YYYY format.                             default value is current date                                  #optional
      -t : 'query'-> only query, 'response' -> only response  & 'all' -> both query & response.         default is 'all'         #optional
      -c : client ip


     Note:
      1. Pattern will be generated by considering number of members. 
         Example: if user specified 2 members (say -m member1.com:member2.com) and query patter is 1000 (say -q 1000) then each member file having 500 patterns. 

      2. For '-t all', 'query + response' considered as one pattern (i.e., if '-m member1.com -q 1000 -t 1000' then total 2000 pattern will be generated).

USAGE
#Created By : Raghavendra MN (rnagaraja@infoblox.com)
#Date : 02/09/2016

my %option = ();
getopts("m:q:d:t:h:c:", \%option);
if (defined($option{h}))
{
  print "\n\n\n$USAGE\n\n\n";
  exit(0);
}
my $member_name = (defined($option{m}))?$option{m}:"ib-11-11-11-11.testing.com";
my $client_ip = (defined($option{c}))?$option{c}:"12.12.12.12";
my $query = (defined($option{q}))?$option{q}:2000;
my $type = (defined($option{t}))?$option{t}:'all';

my $epoc;
if (!defined($option{d})){
  $epoc = time();
}
else {
  my ($m,$d,$y)=split(/:/,$option{d});
  my ($seconds, $minutes, $hours, $day, $month, $year)=(10,10,10,$d,$m,$y);
     $epoc = timegm($seconds, $minutes, $hours, $day, $month-1, $year-1900);
}
my @members = split(/:/,$member_name);
my $mem_count = @members;
chomp($query);
my $query_count = int($query/$mem_count);
# User can modify values for different RR's distribution in following line  but total distribution should be 100
my ($a_count, $aaaa_count,$cname_count,$dname_count,$naptr_count,$ptr_count,$mx_count,$txt_count,$srv_count)=dist(80,12,2,1,1,1,1,1,1);
print "Record Distribution for each file\n A:$a_count\tAAAA:$aaaa_count\tCNAME:$cname_count\tDNAME:$dname_count\tNAPTR:$naptr_count\tPTR:$ptr_count\tMX:$mx_count\tTXT:$txt_count\tSRV:$srv_count\n";
my $new_epoc = int($epoc)+600;

foreach $member_name (@members){
 my $file_name = "captured-dns-".$member_name."-".$epoc."-".$new_epoc;  
 my $domain_count = abs(int($query_count)/($a_count+$aaaa_count+$cname_count+$dname_count+$naptr_count+$ptr_count+$mx_count+$txt_count+$srv_count));

# User can add/modify/remove domains for different query patterns in following line   
 my @domains = ('google.com','sjce.edu','infoblox.com','facebook.com','yahoo.com','gmail.com','flipkart.com','amazon.com','ebay.com','asm.com');
 my @protocol =('UDP','TCP');

 open(MYOUTFILE, "> $file_name");
 for( my $i=1;$i<=$domain_count; $i++)
 {
  my $domain_name=$domains[int(rand(@domains))];
  for( my $j=1;$j<=$a_count; $j++)
  {
   my $port = int(1025 + rand(8974));   
   my $client = get_client();
   my $domain = "arec".int(rand(1000)).".$domain_name";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN A + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN A response: NOERROR -A $domain. 28800 IN A ".get_client().";";  
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
 }
 for( my $j=1;$j<=$aaaa_count; $j++)
 {
   my $port = int(1025 + rand(8974));   
   my $client = get_client();
   my $domain = "aaaa".int(rand(1000)).".$domain_name";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN AAAA + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN AAAA response: NOERROR -A $domain. 28800 IN AAAA 1234::".int(rand(9999)).";";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
 }

 for( my $j=1;$j<=$cname_count; $j++)
 {
   my $port = int(1025 + rand(8974));   
   my $client = get_client();
   my $domain = "cname".int(rand(1000)).".$domain_name";
   my $domain1 = "arec".int(rand(1000)).".$domain_name";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN CNAME + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN CNAME response: NOERROR -A $domain. 28800 IN CNAME $domain1.;";  
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
 }
 for( my $j=1;$j<=$dname_count; $j++)
 {
 my $port = int(1025 + rand(8974));   
   my $client = get_client();
   my $domain = "dname".int(rand(1000)).".$domain_name";
   my $domain1 = "target".int(rand(1000)).".$domain_name";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN DNAME + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN DNAME response: NOERROR -A $domain. 28800 IN DNAME $domain1.;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
 }

 for( my $j=1;$j<=$mx_count; $j++)
 {
   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "mx".int(rand(1000)).".$domain_name";
   my $domain1 = "exchanger".int(rand(1000)).".$domain_name";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN MX + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN MX response: NOERROR -A $domain. 28800 IN MX 10 $domain1.;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
 }

 for( my $j=1;$j<=$txt_count; $j++)
 {
   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "txt".int(rand(1000)).".$domain_name";
   my $txt = int(rand(1000)).".TXT";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN TXT + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN TXT response: NOERROR -A $domain. 28800 IN TXT \"$txt\".;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
 }

 for( my $j=1;$j<=$srv_count; $j++)
 {
   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "srv".int(rand(1000)).".$domain_name";
   my $domain1 = "target".int(rand(1000)).".$domain_name";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN SRV + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN SRV response: NOERROR -A $domain. 28800 IN SRV 1 1 1 $domain1.;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
 }

 for( my $j=1;$j<=$naptr_count; $j++)
 {
   my $port = int(1025 + rand(8974));   
   my $client = get_client();
   my $domain = "naptr".int(rand(1000)).".$domain_name";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN NAPTR + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN NAPTR response: NOERROR -A $domain. 28800 IN NAPTR 10 10  \"U\" \"http+E2U\" \"\" .;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
 }

for( my $j=1;$j<=$ptr_count; $j++)
 {
   my $port = int(1025 + rand(8974));   
   my $client = get_client();
   my $domain = (int(rand(254))+1).".".(int(rand(254))+1).".".(int(rand(254))+1).".".(int(rand(254))+1).".in-addr.arpa.";    #1.0.0.127.in-addr.arpa
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN PTR + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN PTR response: NOERROR -A $domain 28800 IN PTR ".get_client().";";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
  }
 }

#this is created for Automation

   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "arec.automation.com";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN A + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN A response: NOERROR -A $domain. 28800 IN A ".get_client().";";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";

   
   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "aaaa.automation.com";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN AAAA + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN AAAA response: NOERROR -A $domain. 28800 IN AAAA 1234::".int(rand(9999)).";";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";
   
   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "cname.automation.com";
   my $domain1 = "arec.automation.com";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN CNAME + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN CNAME response: NOERROR -A $domain. 28800 IN CNAME $domain1.;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";

   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "dname.automation.com";
   my $domain1 = "target.automation.com";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN DNAME + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN DNAME response: NOERROR -A $domain. 28800 IN DNAME $domain1.;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";

   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "mx.automation.com";
   my $domain1 = "exchanger.automation.com";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN MX + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN MX response: NOERROR -A $domain. 28800 IN MX 10 $domain1.;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";

  
   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "txt.automation.com";
   my $txt = int(rand(1000)).".TXT";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN TXT + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN TXT response: NOERROR -A $domain. 28800 IN TXT \"$txt\".;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";


   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "srv.automation.com";
   my $domain1 = "target.automation.com";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN SRV + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN SRV response: NOERROR -A $domain. 28800 IN SRV 1 1 1 $domain1.;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";

   
   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "naptr.automation.com";
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN NAPTR + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN NAPTR response: NOERROR -A $domain. 28800 IN NAPTR 10 10  \"U\" \"http+E2U\" \"\" .;";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";


   my $port = int(1025 + rand(8974));
   my $client = get_client();
   my $domain = "12.12.12.12.in-addr.arpa.";    #1.0.0.127.in-addr.arpa
   my $temp = get_date()." client $client#".$port.":";
   my $query= $temp." query: $domain IN PTR + ($client)";
   my $response="$temp ".$protocol[int(rand(2))].": query: $domain IN PTR response: NOERROR -A $domain 28800 IN PTR ".get_client().";";
   print MYOUTFILE $type eq 'query' ? $query."\n" : $type eq 'response' ? $response ."\n" : $query."\n".$response ."\n";

close(MYOUTFILE);
system("gzip $file_name");  #making .gz format
}

sub get_date
{
 my $date1 = strftime "%d-%b-%Y", localtime($epoc);
 my $date2 = strftime "%H:%M:%S", localtime($epoc);
 my $sec = `date +%3N`;
 chomp($sec);
 return("$date1 $date2\.$sec");  #returing date in "08-Feb-2016 17-01-01.275" format
}

sub get_client
{
   #return("40.50.60.".int(rand(10)));  #user can change oct1 
   return($client_ip);  # for automation i have modified
}

#calculating pattern Distribution 
sub dist
{
 my @i=@_;
 my $l=@i;
 for($j=0; $j<$l;$j++)
 {
   my $d=int(($i[$j]/100)*$query_count);
   $i[$j]= ($d > 0)? $d : 1;
 } 
 return(@i);
}
