package com.cisco.pxgrid.samples.ise;

import com.cisco.pxgrid.GridConnection;
import com.cisco.pxgrid.model.core.SubnetContentFilter;
import com.cisco.pxgrid.model.net.Session;
import com.cisco.pxgrid.stub.identity.SessionDirectoryFactory;
import com.cisco.pxgrid.stub.identity.SessionDirectoryNotification;

/**
 * Demonstrates how to subscribe to session notifications generated by ISE
 */
public class SessionSubscribe {
	public static void main(String[] args) throws Exception {
		SampleHelper helper = new SampleHelper();
		GridConnection grid = helper.connectWithReconnectionManager();

		SubnetContentFilter filter = helper.promptIpFilters("Filters (ex. '1.0.0.0/255.0.0.0,1234::/16,...' or <enter> for no filter): ");

		if (filter != null) {
			SessionDirectoryFactory.registerNotification(grid, new SampleNotificationHandler(), filter);
		} else {
			SessionDirectoryFactory.registerNotification(grid, new SampleNotificationHandler());
		}

		helper.prompt("press <enter> to disconnect...");
		helper.disconnect();
	}

	public static class SampleNotificationHandler
		implements SessionDirectoryNotification {
		@Override
		public void onChange(Session session) {
			System.out.println("session notification: "); 
			SampleHelper.print(session);
			System.out.println(""); 
		}
	}
}
