#!/usr/bin/python 
# Copyright (c) 2017 Infoblox Inc. All Rights Reserved.
'''
The script prints splunk admin password stored in onedb of reporting grid
Usage get_splunk_admin_password
Example:
To view the new splunk admin password
  get_splunk_admin_password
'''
import getopt
import sys

import infoblox.one.onedb as onedb
from infoblox.one.util import is_real_unit

import infoblox.common.ilog as ilog
import infoblox.common.util as cu
import infoblox.one.util as ou

def usage():
    print __doc__

def main():
    if is_real_unit():
        try:
            db = onedb.Db()
            with db.begin():
                crp = db.call('?reporting.cluster_reporting_properties',
                             {'cluster': ou.get_my_cluster_id()},single=True)
            password = crp.get('new_splunk_admin_passwd', '')
            print password
        except Exception, e:
            ilog.log('get_splunk_admin_password: exception "%s"' % e)
            usage()
    else:
        # chroot is for developers
        import infoblox.reporting.reporting_configuration_constants as rcc
        print 'changeme'
        cu.iexec("touch", rcc.INFOBLOX_REPORTING_PASSWORD_CHANGE_FILE)

if __name__ == '__main__':
    main()
    sys.exit(0)

